//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Entity.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallActivityWarning
    {
        public int Id { get; set; }
        public int CallTypeId { get; set; }
        public int FromNumberOfDays { get; set; }
        public int ToNumberOfDays { get; set; }
        public int WarningSeverity { get; set; }
        public string WarningColour { get; set; }
    
        public virtual CallType CallType { get; set; }
    }
}
