//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Entity.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallAddress
    {
        public CallAddress()
        {
            this.CallActivityAddresses = new HashSet<CallActivityAddress>();
            this.CallAddressNotes = new HashSet<CallAddressNote>();
        }
    
        public int Id { get; set; }
        public string Unit { get; set; }
        public string Number { get; set; }
        public string Street { get; set; }
        public int SuburbId { get; set; }
        public string MelwayRefNo { get; set; }
        public Nullable<int> RouteOrderFromKh { get; set; }
        public Nullable<int> CallGroupId { get; set; }
        public bool IsValid { get; set; }
        public Nullable<System.DateTime> LastCallDate { get; set; }
        public Nullable<int> LastCallActivityStatusId { get; set; }
        public Nullable<double> Longtitude { get; set; }
        public Nullable<double> Latitude { get; set; }
        public string Address { get; set; }
        public string GpsAddress { get; set; }
        public Nullable<int> SuggestedCallGroupId { get; set; }
    
        public virtual ICollection<CallActivityAddress> CallActivityAddresses { get; set; }
        public virtual CallActivityStatu CallActivityStatu { get; set; }
        public virtual CallGroup CallGroup { get; set; }
        public virtual Suburb Suburb { get; set; }
        public virtual ICollection<CallAddressNote> CallAddressNotes { get; set; }
    }
}
