//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Entity.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallGroup
    {
        public CallGroup()
        {
            this.CallActivities = new HashSet<CallActivity>();
            this.CallAddresses = new HashSet<CallAddress>();
        }
    
        public int Id { get; set; }
        public string CallGroupName { get; set; }
        public string GroupCode { get; set; }
        public Nullable<int> CurrentAssignCallActivityId { get; set; }
        public Nullable<int> LastAssignCallActivityId { get; set; }
        public bool AllowAssistantToRelease { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
    
        public virtual ICollection<CallActivity> CallActivities { get; set; }
        public virtual CallActivity CallActivity { get; set; }
        public virtual CallActivity CallActivity1 { get; set; }
        public virtual ICollection<CallAddress> CallAddresses { get; set; }
    }
}
