//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Entity.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallActivityStatu
    {
        public CallActivityStatu()
        {
            this.CallActivityAddresses = new HashSet<CallActivityAddress>();
            this.CallAddresses = new HashSet<CallAddress>();
        }
    
        public int Id { get; set; }
        public string Status { get; set; }
        public string Code { get; set; }
        public bool IsValidAddress { get; set; }
        public bool IsDone { get; set; }
    
        public virtual ICollection<CallActivityAddress> CallActivityAddresses { get; set; }
        public virtual ICollection<CallAddress> CallAddresses { get; set; }
    }
}
