//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Entity.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallActivityAddress
    {
        public int Id { get; set; }
        public int CallActivityId { get; set; }
        public int CallAddressId { get; set; }
        public Nullable<System.DateTime> DateFinished { get; set; }
        public Nullable<int> CallActivityStatusId { get; set; }
        public string Note { get; set; }
    
        public virtual CallActivity CallActivity { get; set; }
        public virtual CallActivityStatu CallActivityStatu { get; set; }
        public virtual CallAddress CallAddress { get; set; }
    }
}
