//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Entity.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cycle
    {
        public Cycle()
        {
            this.SystemReferences = new HashSet<SystemReference>();
            this.CallActivities = new HashSet<CallActivity>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CycleNumber { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string CycleName { get; set; }
    
        public virtual ICollection<SystemReference> SystemReferences { get; set; }
        public virtual ICollection<CallActivity> CallActivities { get; set; }
    }
}
