//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Entity.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class InactiveCallAddress
    {
        public int Id { get; set; }
        public Nullable<int> CallAddressId { get; set; }
        public Nullable<int> CallGroupId { get; set; }
        public Nullable<int> CallStatus { get; set; }
        public Nullable<System.DateTime> DateDeactivated { get; set; }
        public Nullable<int> LastCallActivityId { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
    }
}
