//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Entity.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publisher
    {
        public Publisher()
        {
            this.CallActivities = new HashSet<CallActivity>();
            this.CallActivities1 = new HashSet<CallActivity>();
            this.CallActivities2 = new HashSet<CallActivity>();
            this.CallActivities3 = new HashSet<CallActivity>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string EmailAddress { get; set; }
        public string PhoneNumber { get; set; }
        public string UserName { get; set; }
        public Nullable<int> UserRoleId { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<CallActivity> CallActivities { get; set; }
        public virtual ICollection<CallActivity> CallActivities1 { get; set; }
        public virtual ICollection<CallActivity> CallActivities2 { get; set; }
        public virtual ICollection<CallActivity> CallActivities3 { get; set; }
        public virtual webpages_Roles webpages_Roles { get; set; }
        public virtual webpages_Membership webpages_Membership { get; set; }
    }
}
