//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Entity.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suburb
    {
        public Suburb()
        {
            this.CallAddresses = new HashSet<CallAddress>();
        }
    
        public int Id { get; set; }
        public int StateId { get; set; }
        public string SuburbName { get; set; }
        public string PostCode { get; set; }
    
        public virtual State State { get; set; }
        public virtual ICollection<CallAddress> CallAddresses { get; set; }
    }
}
