//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Entity.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemReference
    {
        public int Id { get; set; }
        public Nullable<int> CurrentCycleId { get; set; }
        public Nullable<int> CurrentCycleNumber { get; set; }
    
        public virtual Cycle Cycle { get; set; }
    }
}
