//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Entity.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwAddress
    {
        public int Id { get; set; }
        public string Address { get; set; }
        public string AddressGps { get; set; }
        public string Unit { get; set; }
        public string Number { get; set; }
        public string Street { get; set; }
        public string SuburbName { get; set; }
        public string StateName { get; set; }
        public string PostCode { get; set; }
        public Nullable<int> CallGroupId { get; set; }
        public string CallGroupName { get; set; }
        public string GroupCode { get; set; }
        public Nullable<int> RouteOrderFromKh { get; set; }
        public int SuburbId { get; set; }
        public Nullable<double> Longtitude { get; set; }
        public Nullable<double> Latitude { get; set; }
        public string MelwayRefNo { get; set; }
        public Nullable<System.DateTime> LastCallDate { get; set; }
    }
}
